#!/bin/sh
VENDOR=archos
DEVICE=archos-gen9
OUTDIR=vendor/$VENDOR/$DEVICE
OUTTREE=device/$VENDOR/$DEVICE
MAKEFILE=$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh


PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l $OUTTREE/proprietary-files.txt | awk {'print $1'}`
for FILE in `cat $OUTTREE/proprietary-files.txt`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    echo "    $OUTDIR/proprietary/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
done

(cat << EOF) > $OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := $OUTDIR/overlay

\$(call inherit-product, $OUTDIR/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > $OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

USE_CAMERA_STUB := false
EOF

MAKEFILE=$OUTTREE/aokp_$DEVICE.mk

(cat << EOF) > $OUTTREE/Android.mk
# Copyright (C) 2011 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
LOCAL_PATH := \$(call my-dir)

include \$(call all-makefiles-under,\$(LOCAL_PATH))
EOF

(cat << EOF) > $OUTTREE/AndroidProducts.mk
# Copyright (C) 2011 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
PRODUCT_MAKEFILES := \$(LOCAL_DIR)/device.mk
EOF

(cat << EOF) > $OUTTREE/kernel
HI
Not Kernel Yet ...
EOF

(cat << EOF) > $OUTTREE/BoardConfig.mk
# Copyright (C) 2011 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
# Use the non-open-source parts, if they're present
-include $OUTDIR/BoardConfigVendor.mk

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_HAVE_BLUETOOTH := true
TARGET_NO_BOOTLOADER := true

TARGET_PREBUILT_KERNEL := $OUTTREE/kernel
BOARD_KERNEL_BASE := 0x80000000
#BOARD_KERNEL_CMDLINE :=

TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := omap4
TARGET_BOOTLOADER_BOARD_NAME := archos

# Recovery
#TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
#TARGET_RECOVERY_UI_LIB := librecovery_ui_panda
# device-specific extensions to the updater binary
#TARGET_RELEASETOOLS_EXTENSIONS := device/ti/panda

BOARD_EGL_CFG := $OUTTREE/prebuilt/lib/egl/egl.cfg

#BOARD_USES_HGL := true
#BOARD_USES_OVERLAY := true
USE_OPENGL_RENDERER := true
#BOARD_USES_PANDA_GRAPHICS := true

# OMAP
OMAP_ENHANCEMENT := true
ifdef OMAP_ENHANCEMENT
COMMON_GLOBAL_CFLAGS += -DOMAP_ENHANCEMENT -DTARGET_OMAP4
endif

#ENABLE_WEBGL := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 268435456
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 16777216
BOARD_USERDATAIMAGE_PARTITION_SIZE := 536870912
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 4096

# Connectivity - Wi-Fi
BOARD_WPA_SUPPLICANT_DRIVER      := NL80211
WPA_SUPPLICANT_VERSION           := VER_0_8_X
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_wl12xx
BOARD_WLAN_DEVICE                := wl12xx_mac80211
BOARD_SOFTAP_DEVICE              := wl12xx_mac80211
WIFI_DRIVER_MODULE_PATH          := "/lib/modules/wl12xx_sdio.ko"
WIFI_DRIVER_MODULE_NAME          := "wl12xx_sdio"
WIFI_FIRMWARE_LOADER             := ""
COMMON_GLOBAL_CFLAGS += -DUSES_TI_MAC80211

#TARGET_PROVIDES_INIT_RC := true
#TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
EOF

(cat << EOF) > $OUTTREE/CleanSpec.mk
# Copyright (C) 2011 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
# ************************************************
# NEWER CLEAN STEPS MUST BE AT THE END OF THE LIST
# ************************************************
\$(call add-clean-step, rm -f \$(PRODUCT_OUT)/system/build.prop)
\$(call add-clean-step, rm -f \$(PRODUCT_OUT)/system/build.prop)
EOF

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
DEVICE_PREBUILT := $OUTTREE/prebuilt

PRODUCT_AAPT_CONFIG := normal mdpi mdpi
PRODUCT_AAPT_PREF_CONFIG := mdpi

ifeq (\$(TARGET_PREBUILT_KERNEL),)
LOCAL_KERNEL := $OUTTREE/kernel
else
LOCAL_KERNEL := \$(TARGET_PREBUILT_KERNEL)
endif
PRODUCT_COPY_FILES = \\
        \$(LOCAL_KERNEL):kernel
PRODUCT_COPY_FILES += \\
        frameworks/base/data/etc/android.hardware.audio.low_latency.xml:/system/etc/permissions/android.hardware.audio.low_latency.xml \\
        frameworks/base/data/etc/android.hardware.camera.autofocus.xml:/system/etc/permissions/android.hardware.camera.autofocus.xml \\
        frameworks/base/data/etc/android.hardware.camera.flash-autofocus.xml:/system/etc/permissions/android.hardware.camera.flash-autofocus.xml \\
        frameworks/base/data/etc/android.hardware.camera.front.xml:/system/etc/permissions/android.hardware.camera.front.xml \\
        frameworks/base/data/etc/android.hardware.camera.xml:/system/etc/permissions/android.hardware.camera.xml \\
        frameworks/base/data/etc/android.hardware.location.gps.xml:/system/etc/permissions/android.hardware.location.gps.xml \\
        frameworks/base/data/etc/android.hardware.location.xml:/system/etc/permissions/android.hardware.location.xml \\
        frameworks/base/data/etc/android.hardware.sensor.light.xml:/system/etc/permissions/android.hardware.sensor.light.xml \\
        frameworks/base/data/etc/android.hardware.telephony.gsm.xml:/system/etc/permissions/android.hardware.telephony.gsm.xml \\
        packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml \\
        frameworks/base/data/etc/android.hardware.touchscreen.multitouch.distinct.xml:/system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \\
        frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:/system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \\
        frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \\
        frameworks/base/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml \\
        frameworks/base/data/etc/android.hardware.wifi.direct.xml:/system/etc/permissions/android.hardware.wifi.direct.xml \\
        frameworks/base/data/etc/android.hardware.wifi.xml:/system/etc/permissions/android.hardware.wifi.xml \\
        frameworks/base/data/etc/android.software.sip.voip.xml:/system/etc/permissions/android.software.sip.voip.xml \\
        frameworks/base/data/etc/com.tmobile.software.themes.xml:/system/etc/permissions/com.tmobile..software.themes.xml \\
        frameworks/base/data/etc/handheld_core_hardware.xml:/system/etc/permissions/handheld_core_hardware.xml \\
        frameworks/base/data/etc/platform.xml:/system/etc/permissions/platform.xml \\
        frameworks/base/data/etc/tablet_core_hardware.xml:/system/etc/permissions/tablet_core_hardware.xml 

PRODUCT_PACKAGES := \\
        su 

# Wifi
PRODUCT_PACKAGES += \\
        lib_driver_cmd_wl12xx \\
        wlan_loader \\
        wlan_cu \\
        dhcpcd.conf \\
        wpa_supplicant.conf \\
        make_ext4fs \\
	com.android.future.usb.accessory

PRODUCT_PACKAGES += \\
        libinvensense_mpl \\
        hwcomposer.default \\
        parse_hdmi_edid \\
        libedid \\
        audio_policy.default \\
        libaudioutils

PRODUCT_PROPERTY_OVERRIDES := \\
	wifi.interface=wlan0 \\
	hwui.render_dirty_regions=false

PRODUCT_PROPERTY_OVERRIDES += \\
	ro.sf.lcd_density=160 

PRODUCT_CHARACTERISTICS := tablet

DEVICE_PACKAGE_OVERLAYS := \\
        device/archos/archos-gen9/overlay

PRODUCT_TAGS += dalvik.gc.type-precise

PRODUCT_PACKAGES := \\
        LiveWallpapers \\
        LiveWallpapersPicker \\
        VisualizationWallpapers \\
        librs_jni \\
	com.android.future.usb.accessory

## It all gets a bit experiemental here. See if we can enable voice and Sms/Mms
PRODUCT_PACKAGES += \\
        Camera \\
        CMWallpapers \\
        CellBroadcastReceiver \\
        Trebuchet \\
        Development \\
        GestureBuilder \\
        GanOptimizer \\
        FileManager \\
        OpenWnn \\
        PinyinIME \\
        Launcher2 \\
        Music \\
        Tag \\
        Phone \\
        Mms     

PRODUCT_PACKAGES += \\
	audio.a2dp.default \\
	libaudioutils

PRODUCT_PACKAGES += \\
	dhcpcd.conf \\
	TQS_D_1.7.ini \\
	calibrator

# Filesystem management tools
PRODUCT_PACKAGES += \\
	make_ext4fs \\
	setup_fs 

# BlueZ test tools
PRODUCT_PACKAGES += \\
	hciconfig \\
	hcitool

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l $OUTTREE/prebuilt-files.txt | awk {'print $1'}`
for FILE in `cat $OUTTREE/prebuilt-files.txt`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    echo "    \$(DEVICE_PREBUILT)/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
done

echo " 
PRODUCT_NAME := aokp_archos_gen9
PRODUCT_DEVICE := $DEVICE " >> $MAKEFILE


(cat << EOF) > $OUTTREE/device.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
# Live Wallpapers
PRODUCT_PACKAGES += \\
        LiveWallpapers \\
        LiveWallpapersPicker \\
        MagicSmokeWallpapers \\
        VisualizationWallpapers \\
        librs_jni

PRODUCT_PROPERTY_OVERRIDES := \\
        net.dns1=8.8.8.8 \\
        net.dns2=8.8.4.4

PRODUCT_COPY_FILES := \\
        vendor/aokp/prebuilt/bootanimation/bootanimation_1280_800.zip:/system/media/bootanimation.zip

# Inherit from those products. Most specific first.
\$(call inherit-product, \$(SRC_TARGET_DIR)/product/full_base.mk)
\$(call inherit-product, $OUTTREE/aokp_$DEVICE.mk)
\$(call inherit-product, $OUTDIR/$DEVICE-vendor.mk)
\$(call inherit-product, frameworks/base/build/tablet-dalvik-heap.mk)
\$(call inherit-product, hardware/ti/omap4xxx/omap4.mk)
\$(call inherit-product-if-exists, vendor/aokp/configs/common_tablet.mk)
\$(call inherit-product-if-exists, vendor/aokp/configs/gsm.mk)

PRODUCT_NAME := aokp_archos_gen9
PRODUCT_DEVICE := $DEVICE
PRODUCT_BRAND := Android
PRODUCT_MODEL := Archos G9
PRODUCT_MANUFACTURER := Archos on AOKP 
EOF

(cat << EOF) > $OUTTREE/vendorsetup.sh
#
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

#add_lunch_combo aokp_archos_gen9-userdebug
EOF

(cat << EOF) > $OUTTREE/system.prop
dalvik.vm.checkjni=false
dalvik.vm.verify-bytecode=false
persist.service.sv.enable=1
archos.tetherState=off
persist.archos.suspend=enabled
opencore.asmd=1
browser.tioptimization=true
connection.concurrent=10
com.ti.omap_enhancement=true
omap.enhancement=true
ro.opengles.version=131072
tv.hdmi.uicloning.enable=true
media.avos.enable-rtsp=true
media.avos.enable-scanner=true
persist.archos.firmware_name=firmware_archos_it4.aos
ro.archos.daos.product=gen9
ro.com.google.mcc_fallback=262
enable.3d.bypass=0
ro.crypto.state=unsupported
ro.board.tsp_has_calibration=true
ro.telephony.default_network=3
EOF

(cat << EOF) > $OUTTREE/recovery.fstab
# This is fake. The .zip won't complete unless there's a bogus recovery.fstab here.
# mount point	fstype		device

/sdcard		datamedia		/dev/null
/system		ext4		/dev/block/platform/omap/omap_hsmmc.0/by-name/system
/cache		ext4		/dev/block/platform/omap/omap_hsmmc.0/by-name/cache
/data		ext4		/dev/block/platform/omap/omap_hsmmc.0/by-name/userdata
/misc 		emmc 		/dev/block/platform/omap/omap_hsmmc.0/by-name/misc
/boot		emmc		/dev/block/platform/omap/omap_hsmmc.0/by-name/boot
/recovery	emmc		/dev/block/platform/omap/omap_hsmmc.0/by-name/recovery
/sbl		emmc		/dev/block/platform/omap/omap_hsmmc.0/by-name/sbl
/xloader	emmc		/dev/block/platform/omap/omap_hsmmc.0/by-name/xloader
/radio		emmc		/dev/block/platform/omap/omap_hsmmc.0/by-name/radio
EOF


echo "add_lunch_combo aokp_archos_gen9-userdebug" >> vendor/aokp/vendorsetup.sh

chmod a+x $OUTTREE/build.sh

. $OUTTREE/build.sh





